# TODO: this extension has been generated by Claude (mostly). We should check everything work (and most probably debug everything)

module KernelIntrinsicsAMDGPUExt

using AMDGPU
using AMDGPU: LLVMPtr, AS, ROCBackend
using KernelAbstractions
const KA = KernelAbstractions
using LLVM
using LLVM.Interop: @asmcall


import KernelIntrinsics
import KernelIntrinsics: _warpsize
import KernelIntrinsics: _laneid
import KernelIntrinsics.MMA: _mma_hw, CDNAMFMA
# Import parent module and types


# Escape the WHOLE call, not the argument. `Base.Experimental.@overlay` runs
# `macroexpand` on its `def` and then demands a function definition — and `esc(expr)` hands it an
# `Expr(:escape, …)` wrapping the `@inline function …` macrocall, which macroexpand does not
# unwrap. It therefore sees an `:escape` node, not a function, and dies with
# "@overlay requires a function definition". Escaping the enclosing call instead passes the raw
# macrocall through, which @overlay expands correctly.
macro amdgpu_overlay(expr)
    return esc(:(Base.Experimental.@overlay AMDGPU.method_table $expr))
end


Base.Experimental.@overlay AMDGPU.method_table @inline function _warpsize()
    return AMDGPU.Device.wavefrontsize()
end

Base.Experimental.@overlay AMDGPU.method_table @inline function _laneid()
    return AMDGPU.Device.activelane() + 1
end

# Jeton matériel MMA — le SEUL overlay du chemin MMA (cf. src/mma.jl, section
# « Jeton matériel »). Il renvoie un singleton : aucune donnée, donc rien à quoi
# un `undef` puisse s'accrocher, contrairement aux fonctions qui produisaient des
# fragments. Device-only : côté hôte `_mma_hw()` reste `NoHW()` ⇒ fallback.
# Il vaut pour l'extension fp8 aussi (AMDGPU est l'un de ses déclencheurs, donc
# cette extension-ci est forcément chargée) — elle n'a pas à le redéfinir.
Base.Experimental.@overlay AMDGPU.method_table @inline function _mma_hw()
    return CDNAMFMA()
end

include("AMDGPU/device.jl")
include("AMDGPU/scopes_ordering.jl")
include("AMDGPU/shuffle_vote.jl")
include("AMDGPU/vectorization.jl")
include("AMDGPU/sleep.jl")
include("AMDGPU/dynlocalmem.jl")
include("AMDGPU/mma.jl")

end # module KernelIntrinsicsAMDGPUExt
