# TODO: this extension has been generated by Claude (mostly). We should check everything work (and most probably debug everything)

module KernelIntrinsicsAMDGPUExt

using AMDGPU
using AMDGPU: LLVMPtr, AS
using LLVM
using LLVM.Interop: @asmcall


import KernelIntrinsics: _warpsize
import KernelIntrinsics: _laneid
# Import parent module and types


macro amdgpu_overlay(expr)
    return :(Base.Experimental.@overlay AMDGPU.method_table $(esc(expr)))
end


Base.Experimental.@overlay AMDGPU.method_table @inline function _warpsize()
    return AMDGPU.Device.wavefrontsize()
end

Base.Experimental.@overlay AMDGPU.method_table @inline function _laneid()
    return AMDGPU.Device.activelane() + 1
end

include("AMDGPU/device.jl")
include("AMDGPU/scopes_ordering.jl")
include("AMDGPU/shuffle_vote.jl")
include("AMDGPU/vectorization.jl")
include("AMDGPU/sleep.jl")

end # module KernelIntrinsicsAMDGPUExt
