# TODO: this extension has been generated by Claude (mostly). We should check everything work (and most probably debug everything)

module KernelIntrinsicsAMDGPUExt

using AMDGPU
using AMDGPU: LLVMPtr, AS
using LLVM
using LLVM.Interop: @asmcall


import KernelIntrinsics: _warpsize
# Import parent module and types

Base.Experimental.@overlay AMDGPU.method_table @inline function _warpsize()
    return AMDGPU.Device.wavefrontsize()
end
include("AMDGPU/device.jl")
include("AMDGPU/scopes_ordering.jl")
include("AMDGPU/shuffle_vote.jl")
include("AMDGPU/vectorization.jl")

end # module KernelIntrinsicsAMDGPUExt
